<a href="https://colab.research.google.com/github/2303A52102/GenerativeAI_2025/blob/main/2303A52102_Ass_8_3_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
 import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
import pandas as pd
url = 'https://drive.google.com/uc?id=1uutPAkOSYb2Uror1mk2dZUtoYbCgz6DO'
data = pd.read_csv(url)
X = data.drop('quality', axis=1)
y = data['quality']
X = (X - X.min()) / (X.max() - X.min())
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = Sequential([
    Dense(16, activation='sigmoid', input_dim=X_train.shape[1]),  # Fixed input_dim
    Dense(24, activation='sigmoid'),
    Dense(10, activation='sigmoid'),
    Dense(1, activation='sigmoid')
])
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])
history = model.fit(X_train, y_train, epochs=260, batch_size=64, validation_split=0.2)
model.save('wine_quality_ann.h5')
test_loss, test_acc = model.evaluate(X_test, y_test)
y_pred = (model.predict(X_test) > 0.5).astype("int32")

print(f"Test Accuracy: {test_acc:.4f}")
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
loaded_model = tf.keras.models.load_model('wine_quality_ann.h5')
sample = X_test.iloc[0:1]
prediction = loaded_model.predict(sample)
print(f"Predicted Quality: {int(prediction[0][0] > 0.5)}")

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/260
16/16 ━━━━━━━━━━━━━━━━━━━━ 6s 92ms/step - accuracy: 0.0000e+00 - loss: 2.9246 - val_accuracy: 0.0000e+00 - val_loss: 0.8913
Epoch 2/260
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.0000e+00 - loss: 0.3709 - val_accuracy: 0.0000e+00 - val_loss: -1.1350
Epoch 3/260
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.0000e+00 - loss: -1.6308 - val_accuracy: 0.0000e+00 - val_loss: -2.9885
Epoch 4/260
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.0000e+00 - loss: -3.4331 - val_accuracy: 0.0000e+00 - val_loss: -4.7172
Epoch 5/260
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.0000e+00 - loss: -5.1218 - val_accuracy: 0.0000e+00 - val_loss: -6.2983
Epoch 6/260
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.0000e+00 - loss: -6.6758 - val_accuracy: 0.0000e+00 - val_loss: -7.7173
Epoch 7/260
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.0000e+00 - loss: -8.0812 - val_accuracy: 0.0000e+00 - val_loss: -8.9795
Epoch 8/260
16/16 ━━━━━━━━━━━━━━━━━━━

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: -207.0780  
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 
Test Accuracy: 0.0000


/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_

Confusion Matrix:
 [[  0   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0]
 [ 10   0   0   0   0   0   0]
 [130   0   0   0   0   0   0]
 [132   0   0   0   0   0   0]
 [ 42   0   0   0   0   0   0]
 [  5   0   0   0   0   0   0]]
Classification Report:
               precision    recall  f1-score   support

           1       0.00      0.00      0.00       0.0
           3       0.00      0.00      0.00       1.0
           4       0.00      0.00      0.00      10.0
           5       0.00      0.00      0.00     130.0
           6       0.00      0.00      0.00     132.0
           7       0.00      0.00      0.00      42.0
           8       0.00      0.00      0.00       5.0

    accuracy                           0.00     320.0
   macro avg       0.00      0.00      0.00     320.0
weighted avg       0.00      0.00      0.00     320.0

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step
Predicted Quality: 1
